spring:
  application:
    name: ClaimWildCats API

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/claimwildcats_db
    username: root
    password: AACBCIT23
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com.claimwildcats: INFO
    org.springframework.security: WARN
